apiVersion: v1
kind: Pod
metadata:
  name: hub-imageinspector-ws
  labels:
    app: hub-imageinspector-ws
spec:
  containers:
  - name: hub-imageinspector-ws-alpine
    image: blackducksoftware/hub-imageinspector-ws-alpine:0.2.1-SNAPSHOT
    volumeMounts:
    - name: inspector-target-dir
      mountPath: /opt/blackduck/hub-imageinspector-ws/target
    ports:
    - containerPort: 8080
      hostPort: 8080
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
  - name: hub-imageinspector-ws-centos
    image: blackducksoftware/hub-imageinspector-ws-centos:0.2.1-SNAPSHOT
    volumeMounts:
    - name: inspector-target-dir
      mountPath: /opt/blackduck/hub-imageinspector-ws/target
    ports:
    - containerPort: 8081
      hostPort: 8081
    livenessProbe:
      httpGet:
        path: /health
        port: 8081
      initialDelaySeconds: 10
      periodSeconds: 5
  - name: hub-imageinspector-ws-ubuntu
    image: blackducksoftware/hub-imageinspector-ws-ubuntu:0.2.1-SNAPSHOT
    volumeMounts:
    - name: inspector-target-dir
      mountPath: /opt/blackduck/hub-imageinspector-ws/target
    ports:
    - containerPort: 8082
      hostPort: 8082
    livenessProbe:
      httpGet:
        path: /health
        port: 8082
      initialDelaySeconds: 10
      periodSeconds: 5
  volumes:
  - name: inspector-target-dir
    hostPath:
      path: ./build/test/target
      type: Directory
