apiVersion: v1
kind: Service
metadata:
  name: hub-imageinspector-ws
  labels:
    run: hub-imageinspector-ws
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: hub-imageinspector-ws
  type: NodePort
