apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackduck-imageinspector
  labels:
    app: blackduck-imageinspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackduck-imageinspector
  template:
    metadata:
      labels:
        app: blackduck-imageinspector
    spec:
      containers:
      - name: blackduck-imageinspector-alpine
        image: blackducksoftware/blackduck-imageinspector-alpine:3.0.0-SNAPSHOT
        volumeMounts:
        - name: inspector-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8080
          hostPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 60
      - name: blackduck-imageinspector-centos
        image: blackducksoftware/blackduck-imageinspector-centos:3.0.0-SNAPSHOT
        volumeMounts:
        - name: inspector-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8081
          hostPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 60
      - name: blackduck-imageinspector-ubuntu
        image: blackducksoftware/blackduck-imageinspector-ubuntu:3.0.0-SNAPSHOT
        volumeMounts:
        - name: inspector-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8082
          hostPort: 8082
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 60
      volumes:
      - name: inspector-shared-dir
        hostPath:
          path: /Users/billings/tmp/shared
          type: Directory
